[package]
name = "rtinaweekend"
version = "0.1.0"
authors = ["Luigi Mori <l@isidora.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.1"
rand = "0.5.6"
